### ISSUE TITLE
При пополнении суммы до максимума не меняется начальный баланс сберегательного счета в методе add

### ISSUE THREAD

**Issue by Bybalesh** [OAOblat/javaqa-team-diplom-2#10]
# Описание
При использовании метода add в 70 строке кода класса SavingAccount начальный баланс сберегательного счета не изменяется при увеличения суммы до максимального предела
# Локализация дефекта
https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70
## Шаги воспроизведения
1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#LL70) в Idea
2.  Создадим объект класса SavingAccount с:
* начальным балансом initialBalance = 6 000;
* минимальным балансом minBalance = 1 000;
* максимальным балансом maxBalance = 10 000;
* ставкой на остаток rate = 5;
3. Пополним баланс на сумму 4 000;
4. Запустим тест testOverAddBalanceEqualsMax;
5. Смотрим на вывод консоли.
***Ожидаемый результат***: Начальный баланс увеличится на сумму 4 000 и в общем составит 10 000, что равно максимальному предельному лимиту.
***Фактический результат***: Начальный баланс не меняется, остается равен 6 000.
# Скриншот
![image](https://github.com/OAOblat/javaqa-team-diplom-2/assets/109616787/35e70146-13b9-4d27-81b2-e6a76259f15d)
# Локация теста
https://github.com/OAOblat/javaqa-team-diplom-2/blob/9458eb2c44aeb9c1d4dac50d96f13404469ba5b1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L22

##Окружение
* Операционная система: Windows 10 Домашняя для одного языка
* IDE: IntelliJ IDEA 2023.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OAOblat** [comment]
done
