### ISSUE TITLE
После совершения покупки начальный баланс сберегательного счета становится ниже минимального предела в методе pay

### ISSUE THREAD

**Issue by Bybalesh** [OAOblat/javaqa-team-diplom-2#11]
# Описание
При использовании метода в 46 строке кода класса SavingAccount начальный баланс сберегательного счета после совершения покупки становится ниже минимального.
# Локализация дефекта
https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L46
## Шаги воспроизведения
1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#LL70) в Idea
2.  Создадим объект класса SavingAccount с:
* начальным балансом initialBalance = 3 000;
* минимальным балансом minBalance = 1 000;
* максимальным балансом maxBalance = 10 000;
* ставкой на остаток rate = 5;
3. Пополним баланс на сумму 3 000;
4. Запустим тест testOverPayBalanceLowMin;
5. Смотрим на вывод консоли.
***Ожидаемый результат***: Начальный баланс не меняется, остается равен 3 000.
***Фактический результат***: Начальный баланс уменьшается на сумму 3 000 и в общем становится 0, что ниже заданного минимального лимита 1 000.
# Скриншот
![image](https://github.com/OAOblat/javaqa-team-diplom-2/assets/109616787/9439f593-3339-4ca1-b8ef-e7b91a359e16)

# Локация теста
https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L66

##Окружение
* Операционная система: Windows 10 Домашняя для одного языка
* IDE: IntelliJ IDEA 2023.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OAOblat** [comment]
done
