### ISSUE TITLE
Не выкидывает исключение при заданном минимальном балансе больше максимального предела в конструкторе с параметром

### ISSUE THREAD

**Issue by Bybalesh** [OAOblat/javaqa-team-diplom-2#13]
# Описание
При использовании конструктора с параметрами в 24 строке кода класса SavingAccount после установки параметра  минимального баланса больше максимального не появляется исключение IllegalArgumentException
# Локализация дефекта
https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L24
## Шаги воспроизведения
1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70) в Idea
2.  Создадим объект класса SavingAccount с:
* начальным балансом initialBalance = 3 000;
* минимальным балансом minBalance = 10 000;
* максимальным балансом maxBalance = 5 000;
* ставкой на остаток rate = 5;
4. Запустим testMinBalanceComparedMaxBalance;
5. Смотрим на вывод консоли.
***Ожидаемый результат***: Появляется исключение IllegalArgumentException "Минимальный баланс не может быть больше максимального баланса, а у вас: 10 000".
***Фактический результат***: е появляется исключение IllegalArgumentException "Минимальный баланс не может быть больше максимального баланса, а у вас: 10 000".
# Скриншот
![image](https://github.com/OAOblat/javaqa-team-diplom-2/assets/109616787/8cbcb37b-4e62-48f0-9fc7-dfd8616183c8)

# Локация теста
https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L134

##Окружение
* Операционная система: Windows 10 Домашняя для одного языка
* IDE: IntelliJ IDEA 2023.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OAOblat** [comment]
done
