### ISSUE TITLE
Формула для расчета yearChange округляет до десятков (необходимо для единиц) в классе SavingAccount

### ISSUE THREAD

**Issue by Bybalesh** [OAOblat/javaqa-team-diplom-2#14]
# Описание
Формула в методе не работает для округления до целочисленного значения

# Локализация дефекта
https://github.com/OAOblat/javaqa-team-diplom-2/blob/74665881bb717dbdffa020626e748bb741ba3e3b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L105

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/74665881bb717dbdffa020626e748bb741ba3e3b/src/main/java/ru/netology/javaqadiplom/SavingAccount.java)
2. Cоздадим объект класса SavingAccount с:
начальным балансом initialBalance = 290;
минимальным балансом minBalance = 1 000;
максимальным балансом maxBalance = 10 000;
ставкой на остаток rate = 15;
3. Запустим testCalcPercent;
4. Смотрим на вывод консоли.
***Ожидаемый результат***: сумма процентов привелась к целому числу (в данном случае 43)
***Фактический результат***: сумма процентов осталась равна 30 из-за неправильного расчета
# Скриншот
![image](https://github.com/OAOblat/javaqa-team-diplom-2/assets/109616787/68e4824e-b4d1-47d6-8453-ab6abf4550c2)
# Тест на проверку
https://github.com/OAOblat/javaqa-team-diplom-2/blob/74665881bb717dbdffa020626e748bb741ba3e3b/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L168
# Окружение
* Операционная система: Windows 10 Домашняя для одного языка
* IDE: IntelliJ IDEA 2023.1 (Community Edition)
* Java: OpenJDK 11

**Comment by OAOblat** [comment]
done
