### ISSUE TITLE
При пополнении не суммируется начальный баланс сберегательного счета с суммой покупки, а обновляется на сумму покупки

### ISSUE THREAD

**Issue by Bybalesh** [OAOblat/javaqa-team-diplom-2#9]
# Описание
При использовании метода add в 70 строке кода класса SavingAccount начальный баланс сберегательного счета в заданном лимите не увеличивается на сумму покупки, а обновляется на новую сумму равную сумме покупки

# Локация дефекта
https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70

## Шаги воспроизведения

1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#LL70C1-L70C1) в IDEA
2. Создадим объект класса SavingAccount с:
* начальным балансом initialBalance = 4 000;
* минимальным балансом minBalance = 1 000;
* максимальным балансом maxBalance = 10 000;
* ставкой на остаток rate = 5;
3. Пополним баланс на сумму 5 000;
4. Запустим тест shouldAddLessThanMaxBalance;
5. Смотрим на вывод консоли.

***Ожидаемый результат***: Начальный баланс увеличится на сумму 5 000 и в общем составит 9 000, что не превышает заданного максимального.
***Фактический результат***: Начальный баланс не суммируется с суммой пополнения, а изменяется на новую сумму равную сумме добавления 5 000.

# Скриншот
![image](https://github.com/OAOblat/javaqa-team-diplom-2/assets/109616787/37199c49-429e-4aca-a99f-1a30c5796565)

# Локация теста для проверки
https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10

# Окружение
* Операционная система: Windows 10 Домашняя для одного языка
* IDE: IntelliJ IDEA 2023.1 (Community Edition)
* Java: OpenJDK 11

**Comment by Bybalesh** [comment]
> # Описание
> При использовании метода add в 70 строке кода класса SavingAccount начальный баланс сберегательного счета в заданном лимите не увеличивается на сумму покупки, а обновляется на новую сумму равную сумме покупки
> 
> # Локация дефекта
> https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L70
> 
> ## Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/OAOblat/javaqa-team-diplom-2/blob/d1eebb4400f66e4f5eee9f0cfb4fd47c818cf866/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#LL70C1-L70C1) в IDEA
> 2. Создадим объект класса SavingAccount с:
> 
> * начальным балансом initialBalance = 4 000;
> * минимальным балансом minBalance = 1 000;
> * максимальным балансом maxBalance = 10 000;
> * ставкой на остаток rate = 5;
> 
> 3. Пополним баланс на сумму 5 000;
> 4. Запустим тест shouldAddLessThanMaxBalance;
> 5. Смотрим на вывод консоли.
> 
> _**Ожидаемый результат**_: Начальный баланс увеличится на сумму 5 000 и в общем составит 9 000, что не превышает заданного максимального. _**Фактический результат**_: Начальный баланс не суммируется с суммой пополнения, а изменяется на новую сумму равную сумме добавления 5 000.
> 
> # Скриншот
> ![image](https://user-images.githubusercontent.com/109616787/243735410-37199c49-429e-4aca-a99f-1a30c5796565.png)
> 
> # Локация теста для проверки
> https://github.com/OAOblat/javaqa-team-diplom-2/blob/00327a151b9c2edc7e0b4b61fe650dd2ec930994/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L10
> 
> # Окружение
> * Операционная система: Windows 10 Домашняя для одного языка * IDE: IntelliJ IDEA 2023.1 (Community Edition) * Java: OpenJDK 11

**Comment by OAOblat** [comment]
done
